<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N2:definitions name="update_order" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/update_order/update_order" xmlns:WL5G3N0="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:WL5G3N1="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/update_order/update_order" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N3="http://xmlns.oracle.com/pcbpel/adapter/db/sp/update_order">
  <WL5G3N0:partnerLinkType name="update_order_plt">
    <WL5G3N0:role name="update_order_role">
      <WL5G3N0:portType name="WL5G3N1:update_order_ptt"/>
    </WL5G3N0:role>
  </WL5G3N0:partnerLinkType>
  <WL5G3N2:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/update_order" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/update_order/update_order" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/update_order" schemaLocation="../xsd/ROF_update_order_sp.xsd"/>
    </schema>
  </WL5G3N2:types>
  <WL5G3N2:message name="args_in_msg">
    <WL5G3N2:part element="WL5G3N3:InputParameters" name="InputParameters"/>
  </WL5G3N2:message>
  <WL5G3N2:message name="args_out_msg">
    <WL5G3N2:part element="WL5G3N3:OutputParameters" name="OutputParameters"/>
  </WL5G3N2:message>
  <WL5G3N2:portType name="update_order_ptt">
    <WL5G3N2:operation name="update_order">
      <WL5G3N2:input message="WL5G3N1:args_in_msg"/>
      <WL5G3N2:output message="WL5G3N1:args_out_msg"/>
    </WL5G3N2:operation>
  </WL5G3N2:portType>
</WL5G3N2:definitions>
