<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="utl_get_value-concrete" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/utl_get_value/utl_get_value" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/utl_get_value/utl_get_value" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:import location="ROF_utl_get_value.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/utl_get_value/utl_get_value"/>
  <WL5G3N0:binding name="utl_get_value_ptt-binding" type="WL5G3N1:utl_get_value_ptt">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="utl_get_value">
      <WL5G3N2:operation soapAction="utl_get_value"/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="utl_get_value_ptt-bindingQSService">
    <WL5G3N0:port binding="WL5G3N1:utl_get_value_ptt-binding" name="utl_get_value_ptt-bindingQSPort">
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>
