<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N2:definitions name="utl_get_value_list" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/utl_get_value_list/utl_get_value_list" xmlns:WL5G3N0="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:WL5G3N1="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/utl_get_value_list/utl_get_value_list" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N3="http://xmlns.oracle.com/pcbpel/adapter/db/sp/utl_get_value_list">
  <WL5G3N0:partnerLinkType name="utl_get_value_list_plt">
    <WL5G3N0:role name="utl_get_value_list_role">
      <WL5G3N0:portType name="WL5G3N1:utl_get_value_list_ptt"/>
    </WL5G3N0:role>
  </WL5G3N0:partnerLinkType>
  <WL5G3N2:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/utl_get_value_list" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RegObjednavaok/utl_get_value_list/utl_get_value_list" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/utl_get_value_list" schemaLocation="../xsd/ROF_utl_get_value_list_sp.xsd"/>
    </schema>
  </WL5G3N2:types>
  <WL5G3N2:message name="args_in_msg">
    <WL5G3N2:part element="WL5G3N3:InputParametersAlt" name="InputParametersAlt"/>
  </WL5G3N2:message>
  <WL5G3N2:message name="args_out_msg">
    <WL5G3N2:part element="WL5G3N3:OutputParametersAlt" name="OutputParametersAlt"/>
  </WL5G3N2:message>
  <WL5G3N2:portType name="utl_get_value_list_ptt">
    <WL5G3N2:operation name="utl_get_value_list">
      <WL5G3N2:input message="WL5G3N1:args_in_msg"/>
      <WL5G3N2:output message="WL5G3N1:args_out_msg"/>
    </WL5G3N2:operation>
  </WL5G3N2:portType>
</WL5G3N2:definitions>
